version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.WEB
    image: oliverec/oliverbad:bakery-code-web
    environment:
      - API_URL=http://api:80
    ports:
      - "5050:80"

  api:
    build:
      context: .
      dockerfile: Dockerfile.API
    image: oliverec/oliverbad:bakery-code-api
    ports:
      - "6060:80"
